### ISSUE TITLE
colors-tty.sh missing

### ISSUE THREAD

**Issue by kernpinoy** [BaptisteBdn/dotfiles#1]
it seems to be that colors-tty.sh is on your zsh config but it is not present on the repo

**Comment by BaptisteBdn** [comment]
Are you refering to this line : `source ~/.cache/wal/colors-tty.sh` ?
It will be automaticaly generated the first time you use pywal.
Link to the pywal documentation : https://github.com/dylanaraps/pywal/wiki/Getting-Started#applying-the-theme-to-new-terminals

**Comment by kernpinoy** [comment]
I see. Sorry for bothering you 😅 thanks for the clarification!
